config/routes.rb
EindwerkAlpha03::Application.routes.draw do
  resources :participants

  resources :author_roles

  resources :authors

  resources :book_formats

  resources :publishers

  resources :book_editions

  resources :bookstores

  resources :campus_details

  resources :libraries

  resources :loans

  resources :bookworks

  resources :users

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name

  #relations
  has_many :participants
  has_many :author_roles, :through => :participants
end

app/models/author_role.rb
class AuthorRole < ActiveRecord::Base
  attr_accessible :role

  #relations
  has_many :participants
  has_many :authors, :through => :participants
end

app/models/book_edition.rb
class BookEdition < ActiveRecord::Base
  attr_accessible :bookwork_id, :book_format_id, :isbn_nr, :publisher_id, :book_edition

  #relations
  belongs_to :bookwork
  belongs_to :publisher
  belongs_to :book_format

end

app/models/book_format.rb
class BookFormat < ActiveRecord::Base
  attr_accessible :format

  #relations
  has_many :book_editions
end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base
  attr_accessible :address, :name

  #relations
  has_many :bookworks
end

app/models/bookwork.rb
class Bookwork < ActiveRecord::Base
  attr_accessible :title, :library_id, :bookstore_id

  #relations
  has_many :loans
  has_many :users, :through => :loans
  has_many :book_editions
  has_many :participants
  has_many :author_roles, :through => :participants
  has_many :authors, :through => :participants
  belongs_to :library
  belongs_to :bookstore


end

app/models/campus_detail.rb
class CampusDetail < ActiveRecord::Base
  attr_accessible :address, :name

  #relations
  has_many :libraries

end

app/models/library.rb
class Library < ActiveRecord::Base
  attr_accessible :name, :room, :campus_detail_id

  #relations
  has_many :bookworks
  belongs_to :campus_detail

  public
  def library_details
    [name, campus_detail.name].join(" in ")
  end
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  attr_accessible :bookwork_id, :user_id

  #relations
  belongs_to :user
  belongs_to :bookwork
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :author_id, :author_role_id, :bookwork_id

  #relations
  belongs_to :author_role
  belongs_to :author
  belongs_to :bookwork
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  attr_accessible :name

  #relations
  has_many :book_editions
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name

  #relations
  has_many :loans
  has_many :bookworks, :through => :loans

  #dinge
  def full_name
    [first_name,last_name].join(" ")
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(params[:participant])

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_roles_helper.rb
module AuthorRolesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/helpers/bookworks_helper.rb
module BookworksHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/participants/_form.html.erb
<%= semantic_form_for @participant do |f| %>
  <%= f.inputs do %>
    <%= f.input :bookwork %>
    <%= f.input :author %>
    <%= f.input :author_role, :member_label => :role %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Author role</th>
    <th>Bookwork</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participants.each do |participant| %>
  <tr>
    <td><%= participant.author.name %></td>
    <td><%= participant.author_role.role %></td>
    <td><%= participant.bookwork.title %></td>
    <td><%= link_to 'Show', participant %></td>
    <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
    <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @participant.author_id %>
</p>

<p>
  <b>Author role:</b>
  <%= @participant.author_role_id %>
</p>

<p>
  <b>Bookwork:</b>
  <%= @participant.bookwork_id %>
</p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>