config/routes.rb
EindwerkAlpha03::Application.routes.draw do
  resources :participants

  resources :author_roles

  resources :authors

  resources :book_formats

  resources :publishers

  resources :book_editions

  resources :bookstores

  resources :campus_details

  resources :libraries

  resources :loans

  resources :bookworks

  resources :users

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name

  #relations
  has_many :participants
  has_many :author_roles, :through => :participants
end

app/models/author_role.rb
class AuthorRole < ActiveRecord::Base
  attr_accessible :role

  #relations
  has_many :participants
  has_many :authors, :through => :participants
end

app/models/book_edition.rb
class BookEdition < ActiveRecord::Base
  attr_accessible :bookwork_id, :book_format_id, :isbn_nr, :publisher_id, :book_edition

  #relations
  belongs_to :bookwork
  belongs_to :publisher
  belongs_to :book_format

end

app/models/book_format.rb
class BookFormat < ActiveRecord::Base
  attr_accessible :format

  #relations
  has_many :book_editions
end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base
  attr_accessible :address, :name

  #relations
  has_many :bookworks
end

app/models/bookwork.rb
class Bookwork < ActiveRecord::Base
  attr_accessible :title, :library_id, :bookstore_id

  #relations
  has_many :loans
  has_many :users, :through => :loans
  has_many :book_editions
  has_many :participants
  has_many :author_roles, :through => :participants
  has_many :authors, :through => :participants
  belongs_to :library
  belongs_to :bookstore


end

app/models/campus_detail.rb
class CampusDetail < ActiveRecord::Base
  attr_accessible :address, :name

  #relations
  has_many :libraries

end

app/models/library.rb
class Library < ActiveRecord::Base
  attr_accessible :name, :room, :campus_detail_id

  #relations
  has_many :bookworks
  belongs_to :campus_detail

  public
  def library_details
    [name, campus_detail.name].join(" in ")
  end
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  attr_accessible :bookwork_id, :user_id

  #relations
  belongs_to :user
  belongs_to :bookwork
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :author_id, :author_role_id, :bookwork_id

  #relations
  belongs_to :author_role
  belongs_to :author
  belongs_to :bookwork
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  attr_accessible :name

  #relations
  has_many :book_editions
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name

  #relations
  has_many :loans
  has_many :bookworks, :through => :loans

  #dinge
  def full_name
    [first_name,last_name].join(" ")
  end
end

app/controllers/bookstores_controller.rb
class BookstoresController < ApplicationController
  # GET /bookstores
  # GET /bookstores.json
  def index
    @bookstores = Bookstore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookstores }
    end
  end

  # GET /bookstores/1
  # GET /bookstores/1.json
  def show
    @bookstore = Bookstore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bookstore }
    end
  end

  # GET /bookstores/new
  # GET /bookstores/new.json
  def new
    @bookstore = Bookstore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bookstore }
    end
  end

  # GET /bookstores/1/edit
  def edit
    @bookstore = Bookstore.find(params[:id])
  end

  # POST /bookstores
  # POST /bookstores.json
  def create
    @bookstore = Bookstore.new(params[:bookstore])

    respond_to do |format|
      if @bookstore.save
        format.html { redirect_to @bookstore, notice: 'Bookstore was successfully created.' }
        format.json { render json: @bookstore, status: :created, location: @bookstore }
      else
        format.html { render action: "new" }
        format.json { render json: @bookstore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookstores/1
  # PUT /bookstores/1.json
  def update
    @bookstore = Bookstore.find(params[:id])

    respond_to do |format|
      if @bookstore.update_attributes(params[:bookstore])
        format.html { redirect_to @bookstore, notice: 'Bookstore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bookstore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookstores/1
  # DELETE /bookstores/1.json
  def destroy
    @bookstore = Bookstore.find(params[:id])
    @bookstore.destroy

    respond_to do |format|
      format.html { redirect_to bookstores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_roles_helper.rb
module AuthorRolesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_formats_helper.rb
module BookFormatsHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/helpers/bookworks_helper.rb
module BookworksHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookstores/_form.html.erb
<%= semantic_form_for @bookstore do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :address %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/bookstores/edit.html.erb
<h1>Editing bookstore</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookstore %> |
<%= link_to 'Back', bookstores_path %>

app/views/bookstores/index.html.erb
<h1>Listing bookstores</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookstores.each do |bookstore| %>
  <tr>
    <td><%= bookstore.name %></td>
    <td><%= bookstore.address %></td>
    <td><%= link_to 'Show', bookstore %></td>
    <td><%= link_to 'Edit', edit_bookstore_path(bookstore) %></td>
    <td><%= link_to 'Destroy', bookstore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bookstore', new_bookstore_path %>

app/views/bookstores/new.html.erb
<h1>New bookstore</h1>

<%= render 'form' %>

<%= link_to 'Back', bookstores_path %>

app/views/bookstores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bookstore.name %>
</p>

<p>
  <b>Address:</b>
  <%= @bookstore.address %>
</p>


<%= link_to 'Edit', edit_bookstore_path(@bookstore) %> |
<%= link_to 'Back', bookstores_path %>