config/routes.rb
EindwerkAlpha03::Application.routes.draw do
  resources :participants

  resources :author_roles

  resources :authors

  resources :book_formats

  resources :publishers

  resources :book_editions

  resources :bookstores

  resources :campus_details

  resources :libraries

  resources :loans

  resources :bookworks

  resources :users

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name

  #relations
  has_many :participants
  has_many :author_roles, :through => :participants
end

app/models/author_role.rb
class AuthorRole < ActiveRecord::Base
  attr_accessible :role

  #relations
  has_many :participants
  has_many :authors, :through => :participants
end

app/models/book_edition.rb
class BookEdition < ActiveRecord::Base
  attr_accessible :bookwork_id, :book_format_id, :isbn_nr, :publisher_id, :book_edition

  #relations
  belongs_to :bookwork
  belongs_to :publisher
  belongs_to :book_format

end

app/models/book_format.rb
class BookFormat < ActiveRecord::Base
  attr_accessible :format

  #relations
  has_many :book_editions
end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base
  attr_accessible :address, :name

  #relations
  has_many :bookworks
end

app/models/bookwork.rb
class Bookwork < ActiveRecord::Base
  attr_accessible :title, :library_id, :bookstore_id

  #relations
  has_many :loans
  has_many :users, :through => :loans
  has_many :book_editions
  has_many :participants
  has_many :author_roles, :through => :participants
  has_many :authors, :through => :participants
  belongs_to :library
  belongs_to :bookstore


end

app/models/campus_detail.rb
class CampusDetail < ActiveRecord::Base
  attr_accessible :address, :name

  #relations
  has_many :libraries

end

app/models/library.rb
class Library < ActiveRecord::Base
  attr_accessible :name, :room, :campus_detail_id

  #relations
  has_many :bookworks
  belongs_to :campus_detail

  public
  def library_details
    [name, campus_detail.name].join(" in ")
  end
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  attr_accessible :bookwork_id, :user_id

  #relations
  belongs_to :user
  belongs_to :bookwork
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :author_id, :author_role_id, :bookwork_id

  #relations
  belongs_to :author_role
  belongs_to :author
  belongs_to :bookwork
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  attr_accessible :name

  #relations
  has_many :book_editions
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name

  #relations
  has_many :loans
  has_many :bookworks, :through => :loans

  #dinge
  def full_name
    [first_name,last_name].join(" ")
  end
end

app/controllers/book_editions_controller.rb
class BookEditionsController < ApplicationController
  # GET /book_editions
  # GET /book_editions.json
  def index
    @book_editions = BookEdition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @book_editions }
    end
  end

  # GET /book_editions/1
  # GET /book_editions/1.json
  def show
    @book_edition = BookEdition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book_edition }
    end
  end

  # GET /book_editions/new
  # GET /book_editions/new.json
  def new
    @book_edition = BookEdition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book_edition }
    end
  end

  # GET /book_editions/1/edit
  def edit
    @book_edition = BookEdition.find(params[:id])
  end

  # POST /book_editions
  # POST /book_editions.json
  def create
    @book_edition = BookEdition.new(params[:book_edition])

    respond_to do |format|
      if @book_edition.save
        format.html { redirect_to @book_edition, notice: 'Book edition was successfully created.' }
        format.json { render json: @book_edition, status: :created, location: @book_edition }
      else
        format.html { render action: "new" }
        format.json { render json: @book_edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /book_editions/1
  # PUT /book_editions/1.json
  def update
    @book_edition = BookEdition.find(params[:id])

    respond_to do |format|
      if @book_edition.update_attributes(params[:book_edition])
        format.html { redirect_to @book_edition, notice: 'Book edition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book_edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_editions/1
  # DELETE /book_editions/1.json
  def destroy
    @book_edition = BookEdition.find(params[:id])
    @book_edition.destroy

    respond_to do |format|
      format.html { redirect_to book_editions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_roles_helper.rb
module AuthorRolesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_editions_helper.rb
module BookEditionsHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/helpers/bookworks_helper.rb
module BookworksHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_editions/_form.html.erb
<%= semantic_form_for @book_edition do |f| %>
  <%= f.inputs do %>
    <%= f.input :bookwork %>
    <%= f.input :book_edition %>
    <%= f.input :isbn_nr %>
    <%= f.input :book_format, :member_label => :format %>
    <%= f.input :publisher %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/book_editions/edit.html.erb
<h1>Editing book_edition</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_edition %> |
<%= link_to 'Back', book_editions_path %>

app/views/book_editions/index.html.erb
<h1>Listing book_editions</h1>

<table>
  <tr>
    <th>book edition</th>
    <th>Isbn nr</th>
    <th>Format</th>
    <th>Bookwork</th>
    <th>Publisher</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @book_editions.each do |book_edition| %>
  <tr>
    <td><%= book_edition.book_edition %></td>
    <td><%= book_edition.isbn_nr %></td>
    <td><%= book_edition.book_format.format %></td>
    <td><%= book_edition.bookwork.title %></td>
    <td><%= book_edition.publisher.name %></td>
    <td><%= link_to 'Show', book_edition %></td>
    <td><%= link_to 'Edit', edit_book_edition_path(book_edition) %></td>
    <td><%= link_to 'Destroy', book_edition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book edition', new_book_edition_path %>

app/views/book_editions/new.html.erb
<h1>New book_edition</h1>

<%= render 'form' %>

<%= link_to 'Back', book_editions_path %>

app/views/book_editions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Isbn nr:</b>
  <%= @book_edition.isbn_nr %>
</p>

<p>
  <b>Format:</b>
  <%= @book_edition.book_format %>
</p>

<p>
  <b>Bookwork:</b>
  <%= @book_edition.bookwork_id %>
</p>

<p>
  <b>Publisher:</b>
  <%= @book_edition.publisher_id %>
</p>


<%= link_to 'Edit', edit_book_edition_path(@book_edition) %> |
<%= link_to 'Back', book_editions_path %>